// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package main

import (
	"encoding/json"
)

// AddressChange defines model for AddressChange.
type AddressChange struct {
	ChangeType string `json:"changeType"`
	NewAddress string `json:"newAddress"`
}

// Change defines model for Change.
type Change struct {
	ChangeType string `json:"changeType"`
}

// NameChange defines model for NameChange.
type NameChange struct {
	ChangeType string `json:"changeType"`
	NewName    string `json:"newName"`
}

// ChangeJSONBody defines parameters for Change.
type ChangeJSONBody struct {
	union json.RawMessage
}

// ChangeJSONRequestBody defines body for Change for application/json ContentType.
type ChangeJSONRequestBody ChangeJSONBody
